name: 'format-ansi tests'
on:
  - push

jobs:
  install-quicklisp-on-tier-1-platforms:
    strategy:
      matrix:
        implementation: ['abcl', 'ecl', 'sbcl']
        os: ['ubuntu-latest']
    runs-on: '${{ matrix.os }}'
    name: 'Install Common Lisp'
    steps:
      - uses: actions/checkout@v3
      - name: 'Install MacPorts'
        if: runner.os == 'macOS'
        uses: melusina-org/setup-macports@v1
      - uses: melusina-org/setup-common-lisp@v1
        with:
          implementation: '${{ matrix.implementation }}'
      - uses: melusina-org/setup-quicklisp@v1
        id: 'quicklisp'
        with:
          implementation: '${{ matrix.implementation }}'
      - name: 'Validate installed implementation'
        run: |
          test -d '${{ steps.quicklisp.outputs.quicklisp-home }}'
          test -d '${{ steps.quicklisp.outputs.quicklisp-local-projects }}'
      - uses: melusina-org/asdf-operate@v1
        with:
          implementation: '${{ matrix.implementation }}'
          system: 'format-ansi'
          operation: 'asdf:test-op'
